version: '3.3'

services:
  master:
    image: crawlabteam/crawlab
    container_name: crawlab_master
    restart: always
    environment:
      CRAWLAB_NODE_MASTER: "Y"  # Y: master node
      CRAWLAB_MONGO_HOST: "mongo"  # mongo host address. In the docker compose network, directly refer to the service name
      CRAWLAB_MONGO_PORT: "27017"  # mongo port
      CRAWLAB_MONGO_DB: "crawlab"  # mongo database
      CRAWLAB_MONGO_USERNAME: "gx"  # mongo username
      CRAWLAB_MONGO_PASSWORD: "gx301213"  # mongo password
      CRAWLAB_MONGO_AUTHSOURCE: "admin"  # mongo auth source
    volumes:
      - "./.crawlab/master:/root/.crawlab"  # persistent crawlab metadata
      - "./crawlab/master:/data"  # persistent crawlab data
      - "./crawlab/log:/var/log/crawlab" # log persistent
    ports:
      - "8080:8080"  # exposed api port
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "gx"  # mongo username
      MONGO_INITDB_ROOT_PASSWORD: "gx301213"  # mongo password
    volumes:
      - "./.crawlab/master:/root/.crawlab"  # persistent crawlab metadata
      - "./crawlab/mongo/data/db:/data/db"  # persistent mongo data
    ports:
      - "17017:27017"  # expose mongo port to host machine
