version: '3.8'

services:
  mongodb:
    image: mongo:6.0  # Official MongoDB image
    container_name: mongodb
    restart: always  # Auto-restart on failure
    ports:
      - "27017:27017"  # Host:Container port mapping
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # Root username (customize!)
      MONGO_INITDB_ROOT_PASSWORD: example  # Root password (customize!)
    volumes:
      - mongo_data:/data/db  # Persist data to a named volume
    networks:
      - mongo_network

  # Optional: Add MongoDB Express (web UI) for management
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - mongo_network

volumes:
  mongo_data:  # Named volume for MongoDB data persistence

networks:
  mongo_network:  # Dedicated network for MongoDB services